#+title: Ethersync Transient Org Notes

* Key Terms
** Transient
- Taken from the Transient Showcase Guide
  - A 'Transient' is temporary keymap and the popup UI for displaying that keymap.

    A transient consists of a prefix command and at least one suffix command, though usually a transient has several infix and suffix commands.


4.1 Technical Introduction
==========================

Taking inspiration from prefix keys and prefix arguments, Transient
implements a similar abstraction involving a prefix command, infix
arguments and suffix commands.



   Transient can be used to implement simple “command dispatchers”.  The
main benefit then is that the user can see all the available commands in
a temporarily shown buffer, which can be thought of as a “menu”.  That
is useful by itself because it frees the user from having to remember
all the keys that are valid after a certain prefix key or command.
Magit’s ‘magit-dispatch’ (on ‘C-x M-g’) command is an example of using
Transient to merely implement a command dispatcher.




   When the user calls a transient prefix command, a transient
(temporary) keymap is activated, which binds the transient’s infix and
suffix commands, and functions that control the transient state are
added to ‘pre-command-hook’ and ‘post-command-hook’.  The available
suffix and infix commands and their state are shown in a menu buffer
until the transient state is exited by invoking a suffix command.

user calls a transient prefix command

a transient (temporary) keymap is activated

functions that control the transient state are added to ‘pre-command-hook’


functions that control the transient state are added to ‘post-command-hook’


The available suffix and infix commands and their state are shown in a menu buffer until the transient state is exited by invoking a suffix command.

- There are 3 key parts of the Transient:

** The Prefix
- The *prefix* is the command you invoke first, such as ~magit-dispatch~

  The Transient package provides a macro that allows you to define prefixes for your specific project. This macro is called =transient-define-prefix= (defined 1025 of =transient.el= in the transient package). The magit devs used this macro to define their prefixes (for example, the ~magit-dispatch~ prefix is defined line 332 of =magit.el= in the magit package).

*** Prefix Source Code

#+begin_src emacs-lisp :tangle yes

(defmacro transient-define-prefix (name arglist &rest args)
  "Define NAME as a transient prefix command.

ARGLIST are the arguments that command takes.
DOCSTRING is the documentation string and is optional.

These arguments can optionally be followed by key-value pairs.
Each key has to be a keyword symbol, either `:class' or a keyword
argument supported by the constructor of that class.  The
`transient-prefix' class is used if the class is not specified
explicitly.

GROUPs add key bindings for infix and suffix commands and specify
how these bindings are presented in the menu buffer.  At least
one GROUP has to be specified.  See info node `(transient)Binding
Suffix and Infix Commands'.

The BODY is optional.  If it is omitted, then ARGLIST is also
ignored and the function definition becomes:

  (lambda ()
    (interactive)
    (transient-setup \\='NAME))

If BODY is specified, then it must begin with an `interactive'
form that matches ARGLIST, and it must call `transient-setup'.
It may however call that function only when some condition is
satisfied; that is one of the reason why you might want to use
an explicit BODY.

All transients have a (possibly nil) value, which is exported
when suffix commands are called, so that they can consume that
value.  For some transients it might be necessary to have a sort
of secondary value, called a scope.  Such a scope would usually
be set in the commands `interactive' form and has to be passed
to the setup function:

  (transient-setup \\='NAME nil nil :scope SCOPE)

\(fn NAME ARGLIST [DOCSTRING] [KEYWORD VALUE]... GROUP... [BODY...])"
  (declare (debug ( &define name lambda-list
                    [&optional lambda-doc]
                    [&rest keywordp sexp]
                    [&rest vectorp]
                    [&optional ("interactive" interactive) def-body]))
           (indent defun)
           (doc-string 3))
  (pcase-let
      ((`(,class ,slots ,groups ,docstr ,body ,interactive-only)
        (transient--expand-define-args args arglist 'transient-define-prefix)))
    `(progn
       (defalias ',name
         ,(if body
              `(lambda ,arglist ,@body)
            `(lambda ()
               (interactive)
               (transient-setup ',name))))
       (put ',name 'interactive-only ,interactive-only)
       (put ',name 'function-documentation ,docstr)
       (put ',name 'transient--prefix
            (,(or class 'transient-prefix) :command ',name ,@slots))
       (transient--set-layout
        ',name
        (list ,@(mapcan (lambda (s) (transient--parse-child name s)) groups))))))

#+end_src


*** Prefix Documentation

4.2 Defining Transients (From Transient Documentation)
=======================

A transient consists of a prefix command and at least one suffix
command, though usually a transient has several infix and suffix
commands.  The below macro defines the transient prefix command *and*
binds the transient’s infix and suffix commands.  In other words, it
defines the complete transient, not just the transient prefix command
that is used to invoke that transient.

 -- Macro: transient-define-prefix name arglist [docstring] [keyword
          value]... group... [body...]
     This macro defines NAME as a transient prefix command and binds the
     transient’s infix and suffix commands.

     ARGLIST are the arguments that the prefix command takes.  DOCSTRING
     is the documentation string and is optional.

     These arguments can optionally be followed by keyword-value pairs.
     Each key has to be a keyword symbol, either ‘:class’ or a keyword
     argument supported by the constructor of that class.  The
     ‘transient-prefix’ class is used if the class is not specified
     explicitly.

     GROUPs add key bindings for infix and suffix commands and specify
     how these bindings are presented in the menu buffer.  At least one
     GROUP has to be specified.  See *note Binding Suffix and Infix
     Commands::.

     The BODY is optional.  If it is omitted, then ARGLIST is ignored
     and the function definition becomes:

          (lambda ()
            (interactive)
            (transient-setup 'NAME))

     If BODY is specified, then it must begin with an ‘interactive’ form
     that matches ARGLIST, and it must call ‘transient-setup’.  It may,
     however, call that function only when some condition is satisfied.

     All transients have a (possibly ‘nil’) value, which is exported
     when suffix commands are called, so that they can consume that
     value.  For some transients it might be necessary to have a sort of
     secondary value, called a “scope”.  Such a scope would usually be
     set in the command’s ‘interactive’ form and has to be passed to the
     setup function:

          (transient-setup 'NAME nil nil :scope SCOPE)

     For example, the scope of the ‘magit-branch-configure’ transient is
     the branch whose variables are being configured.

   Sometimes multiple prefix commands share a common set of suffixes.
For example, while ‘magit-diff’ (‘d’) and ‘magit-diff-refresh’ (‘D’)
offer different suffixes to actually create or update a diff, they both
offer the same infix arguments to control how that diff is formatted.
Such shared groups should be defined using ‘transient-define-group’ and
then included in multiple prefixes, by using the symbol that identifies
the group in the prefix definition, in a location where you would
otherwise use a group vector.  If an included group is placed at the
top-level of a prefix (as opposed of inside inside a vector as a child
group), then the symbol should be quoted.

 -- Macro: transient-define-group name group...
     This macro define one or more groups and stores them in symbol
     NAME.  GROUPs have the same form as for ‘transient-define-prefix’.


  - For context, the ~magit dispatch~ prefix is the prefix that is called when the user hits =?= inside the magit status buffer (so, once the user has hit =SPC g g= to get to the magit status buffer, hitting =?= calls the ~magit-dispatch~ prefix. Once the prefix loads, presenting all the command options, it awaits the suffix, aka the next command, described below)

** The Suffix
- A *suffix* is a command displayed in the transient UI, such as ~magit-stage~

  Suffix commands usually quit the transient and they may use the values set by the infix commands, i.e., the infix *arguments*.

*** Suffix Source Code

    #+begin_src emacs-lisp :tangle yes

(defmacro transient-define-suffix (name arglist &rest args)
  "Define NAME as a transient suffix command.

ARGLIST are the arguments that the command takes.
DOCSTRING is the documentation string and is optional.

These arguments can optionally be followed by key-value pairs.
Each key has to be a keyword symbol, either `:class' or a
keyword argument supported by the constructor of that class.
The `transient-suffix' class is used if the class is not
specified explicitly.

The BODY must begin with an `interactive' form that matches
ARGLIST.  The infix arguments are usually accessed by using
`transient-args' inside `interactive'.

\(fn NAME ARGLIST [DOCSTRING] [KEYWORD VALUE]... [BODY...])"
  (declare (debug ( &define name lambda-list
                    [&optional lambda-doc]
                    [&rest keywordp sexp]
                    [&optional ("interactive" interactive) def-body]))
           (indent defun)
           (doc-string 3))
  (pcase-let
      ((`(,class ,slots ,_ ,docstr ,body ,interactive-only)
        (transient--expand-define-args args arglist 'transient-define-suffix)))
    `(progn
       (defalias ',name
         ,(if (and (not body) class (oref-default class definition))
              `(oref-default ',class definition)
            `(lambda ,arglist ,@body)))
       (put ',name 'interactive-only ,interactive-only)
       (put ',name 'function-documentation ,docstr)
       (put ',name 'transient--suffix
            (,(or class 'transient-suffix) :command ',name ,@slots)))))
    #+end_src



*** Suffix Documentation

4.2 Defining Transients (From Transient Documentation)
=======================


   Calling a suffix command usually causes the transient to be exited;
the transient keymaps and hook functions are removed, the menu buffer no
longer shows information about the (no longer bound) suffix commands,
the values of some public global variables are set, while some internal
global variables are unset, and finally the command is actually called.
Suffix commands can also be configured to not exit the transient.

   A suffix command can, but does not have to, use the infix arguments
in much the same way any command can choose to use or ignore the prefix
arguments.  For a suffix command that was invoked from a transient, the
variable ‘transient-current-suffixes’ and the function ‘transient-args’
serve about the same purpose as the variables ‘prefix-arg’ and
‘current-prefix-arg’ do for any command that was called after the prefix
arguments have been set using a command such as ‘universal-argument’.


  The Transient package provides a macro that allows you to define suffixes for your specific project. This macro is called =transient-define-suffix= (defined 1086 of =transient.el= in the transient package). I have not found where / if the magit devs used this macro to define their suffixes.

  The hello transient user input sequence is:

  =Prefix -> Suffix=


** The Infix
- Some suffixes need to hold state, toggling or storing an argument.  Infixes are specialized suffixes to set and hold state.
- Infix commands set some value (which is then shown in the menu buffer), without leaving the transient.

A user input sequence with infixes:

=Prefix -> Infix -> Infix -> Suffix=


*** Infix Source Code

#+begin_src emacs-lisp :tangle yes

(defmacro transient-define-infix (name arglist &rest args)
  "Define NAME as a transient infix command.

ARGLIST is always ignored and reserved for future use.
DOCSTRING is the documentation string and is optional.

At least one key-value pair is required.  All transient infix
commands are equal to each other (but not eq).  It is meaning-
less to define an infix command, without providing at least one
keyword argument (usually `:argument' or `:variable', depending
on the class).  The suffix class defaults to `transient-switch'
and can be set using the `:class' keyword.

The function definitions is always:

  (lambda ()
    (interactive)
    (let ((obj (transient-suffix-object)))
      (transient-infix-set obj (transient-infix-read obj)))
    (transient--show))

`transient-infix-read' and `transient-infix-set' are generic
functions.  Different infix commands behave differently because
the concrete methods are different for different infix command
classes.  In rare case the above command function might not be
suitable, even if you define your own infix command class.  In
that case you have to use `transient-define-suffix' to define
the infix command and use t as the value of the `:transient'
keyword.

\(fn NAME ARGLIST [DOCSTRING] KEYWORD VALUE [KEYWORD VALUE]...)"
  (declare (debug ( &define name lambda-list
                    [&optional lambda-doc]
                    keywordp sexp
                    [&rest keywordp sexp]))
           (indent defun)
           (doc-string 3))
  (pcase-let
      ((`(,class ,slots ,_ ,docstr ,_ ,interactive-only)
        (transient--expand-define-args args arglist 'transient-define-infix t)))
    `(progn
       (defalias ',name #'transient--default-infix-command)
       (put ',name 'interactive-only ,interactive-only)
       (put ',name 'completion-predicate #'transient--suffix-only)
       (put ',name 'function-documentation ,docstr)
       (put ',name 'transient--suffix
            (,(or class 'transient-switch) :command ',name ,@slots)))))
#+end_src

* Groups & Layouts
To define a transient, you need at least one group.  Groups are vectors, delimited as =[ ...group... ]=.

There is basic layout support and you can use it to collect or differentiate commands.

If you begin a group vector with a string, you get a group heading.  Groups also support some [[https://magit.vc/manual/transient/Group-Specifications.html#Group-Specifications][properties]].  The [[elisp:(describe-symbol transient-group)][group class]] also has a lot of information.




* Helpful Functions

Yes or no input function: (Defined line 151 of `magit-process.el`)

#+BEGIN_SRC elisp
    (defcustom magit-process-yes-or-no-prompt-regexp
    (eval-when-compile
        (concat " [([]"
                "\\([Yy]\\(?:es\\)?\\)"
                "[/|]"
                "\\([Nn]o?\\)"
                ;; OpenSSH v8 prints this.  See #3969.
                "\\(?:/\\[fingerprint\\]\\)?"
                "[])] ?[?:]? ?$"))
    "Regexp matching Yes-or-No prompts of Git and its subprocesses."
    :package-version '(magit . "2.1.0")
    :group 'magit-process
    :type 'regexp)
#+END_SRC







#+BEGIN_SRC elisp
(progn 1 3 5 4 7 2)
#+END_SRC

#+RESULTS:
: 2





* Ethersync Transient Code Testing:


(transient-define-prefix ethersync-dispatch()
  "Invoke an Ethersync command from a list of available commands."
  ["Available Commands"
   ("s" "Share"          ether-share)
    ("j" "Join"           ether-join)
    ("c" "Status"         ether-status)
    ])


;;; Evaluating Last sexp produces this:
;;; => [2 nil ([transient-column (:description "Available Commands") ((transient-suffix :key "s" :description "Share" :command ether-share) (transient-suffix : key "j" :description "Join" :command ether-join) (transient-suffix :key "c" :description "Status" : command ether-status) ) ]) ]
;;;
;;; So, when the prefix is defined, it defines an instance of the ~transient-suffix~ class for each key mapping. The definition of transient suffix is pasted below:
;;;
;;; (defclass transient-suffix (transient-child)
;;;   ((definition  :allocation :class    :initform nil)
;;;    (key         :initarg :key)
;;;    (command     :initarg :command)
;;;    (transient   :initarg :transient)
;;;    (format      :initarg :format      :initform " %k %d")
;;;    (description :initarg :description :initform nil)
;;;    (face        :initarg :face        :initform nil)
;;;    (show-help   :initarg :show-help   :initform nil)
;;;    (summary     :initarg :summary     :initform nil))
;;;   "Superclass for suffix command.")



I get this error when evaluation the prefix in a minibuffer:

< insert error here >


This is why chat says I'm getting the error:
