#+title: Magit Buffer Mod

* Key Terms
- Taken from the Transient Showcase Guide
  - A 'Transient' is temporary keymap and the popup UI for displaying that keymap.
  - There are 3 key parts of the Transient:
** The Prefix
- The *prefix* is the command you invoke first, such as ~magit-dispatch~

  The Transient package provides a macro that allows you to define prefixes for your specific project. This macro is called =transient-define-prefix= (defined 1025 of =transient.el= in the transient package). The magit devs used this macro to define their prefixes (for example, the ~magit-dispatch~ prefix is defined line 332 of =magit.el= in the magit package).


4.2 Defining Transients (From Transient Documentation)
=======================

A transient consists of a prefix command and at least one suffix
command, though usually a transient has several infix and suffix
commands.  The below macro defines the transient prefix command *and*
binds the transient’s infix and suffix commands.  In other words, it
defines the complete transient, not just the transient prefix command
that is used to invoke that transient.

 -- Macro: transient-define-prefix name arglist [docstring] [keyword
          value]... group... [body...]
     This macro defines NAME as a transient prefix command and binds the
     transient’s infix and suffix commands.

     ARGLIST are the arguments that the prefix command takes.  DOCSTRING
     is the documentation string and is optional.

     These arguments can optionally be followed by keyword-value pairs.
     Each key has to be a keyword symbol, either ‘:class’ or a keyword
     argument supported by the constructor of that class.  The
     ‘transient-prefix’ class is used if the class is not specified
     explicitly.

     GROUPs add key bindings for infix and suffix commands and specify
     how these bindings are presented in the menu buffer.  At least one
     GROUP has to be specified.  See *note Binding Suffix and Infix
     Commands::.

     The BODY is optional.  If it is omitted, then ARGLIST is ignored
     and the function definition becomes:

          (lambda ()
            (interactive)
            (transient-setup 'NAME))

     If BODY is specified, then it must begin with an ‘interactive’ form
     that matches ARGLIST, and it must call ‘transient-setup’.  It may,
     however, call that function only when some condition is satisfied.

     All transients have a (possibly ‘nil’) value, which is exported
     when suffix commands are called, so that they can consume that
     value.  For some transients it might be necessary to have a sort of
     secondary value, called a “scope”.  Such a scope would usually be
     set in the command’s ‘interactive’ form and has to be passed to the
     setup function:

          (transient-setup 'NAME nil nil :scope SCOPE)

     For example, the scope of the ‘magit-branch-configure’ transient is
     the branch whose variables are being configured.

   Sometimes multiple prefix commands share a common set of suffixes.
For example, while ‘magit-diff’ (‘d’) and ‘magit-diff-refresh’ (‘D’)
offer different suffixes to actually create or update a diff, they both
offer the same infix arguments to control how that diff is formatted.
Such shared groups should be defined using ‘transient-define-group’ and
then included in multiple prefixes, by using the symbol that identifies
the group in the prefix definition, in a location where you would
otherwise use a group vector.  If an included group is placed at the
top-level of a prefix (as opposed of inside inside a vector as a child
group), then the symbol should be quoted.

 -- Macro: transient-define-group name group...
     This macro define one or more groups and stores them in symbol
     NAME.  GROUPs have the same form as for ‘transient-define-prefix’.


  - For context, the ~magit dispatch~ prefix is the prefix that is called when the user hits =?= inside the magit status buffer (so, once the user has hit =SPC g g= to get to the magit status buffer, hitting =?= calls the ~magit-dispatch~ prefix. Once the prefix loads, presenting all the command options, it awaits the suffix, aka the next command, described below)

** The Suffix
- A *suffix* is a command displayed in the transient UI, such as ~magit-stage~

  Suffix commands usually quit the transient and they may use the values set by the infix commands, i.e., the infix *arguments*.

  The Transient package provides a macro that allows you to define suffixes for your specific project. This macro is called =transient-define-suffix= (defined 1086 of =transient.el= in the transient package). I have not found where / if the magit devs used this macro to define their suffixes.

  The hello transient user input sequence is:

  =Prefix -> Suffix=


** The Infix
- Some suffixes need to hold state, toggling or storing an argument.  Infixes are specialized suffixes to set and hold state.
- Infix commands set some value (which is then shown in the menu buffer), without leaving the transient.

A user input sequence with infixes:

=Prefix -> Infix -> Infix -> Suffix=


* Groups & Layouts
To define a transient, you need at least one group.  Groups are vectors, delimited as =[ ...group... ]=.

There is basic layout support and you can use it to collect or differentiate commands.

If you begin a group vector with a string, you get a group heading.  Groups also support some [[https://magit.vc/manual/transient/Group-Specifications.html#Group-Specifications][properties]].  The [[elisp:(describe-symbol transient-group)][group class]] also has a lot of information.




#+BEGIN_SRC elisp
(progn 1 3 5 4 7 2)
#+END_SRC

#+RESULTS:
: 2
