sequence_objects {
  Emacs

  eclient: ethersync client
  edaemon: ethersync daemon
}

style: {
  unix: {
    style {
      stroke: red
    }
  }

  elisp: {
    style {
      stroke: purple
    }
  }

  shell-cmd: {
    style {
      stroke: black
    }
  }

}
