#+title: Magit Buffer Mod

* Key Terms
- Taken from the Transient Showcase Guide
  - A 'Transient' is temporary keymap and the popup UI for displaying that keymap.
  - There are 3 key parts of the Transient:
** The Prefix
- The *prefix* is the command you invoke first, such as ~magit-dispatch~

  The Transient package provides a macro that allows you to define prefixes for your specific project. This macro is called =transient-define-prefix= (defined 1025 of =transient.el= in the transient package). The magit devs used this macro to define their prefixes (for example, the ~magit-dispatch~ prefix is defined line 332 of =magit.el= in the magit package).

  - For context, the ~magit dispatch~ prefix is the prefix that is called when the user hits =?= inside the magit status buffer (so, once the user has hit =SPC g g= to get to the magit status buffer, hitting =?= calls the ~magit-dispatch~ prefix. Once the prefix loads, presenting all the command options, it awaits the suffix, aka the next command, described below)

** The Suffix
- A *suffix* is a command displayed in the transient UI, such as ~magit-stage~

  The Transient package provides a macro that allows you to define suffixes for your specific project. This macro is called =transient-define-suffix= (defined 1086 of =transient.el= in the transient package). I have not found where / if the magit devs used this macro to define their suffixes.

  The hello transient user input sequence is:

  =Prefix -> Suffix=


** The Infix
- Some suffixes need to hold state, toggling or storing an argument.  Infixes are specialized suffixes to set and hold state.

  A user input sequence with infixes:

  =Prefix -> Infix -> Infix -> Suffix=


* Groups & Layouts
To define a transient, you need at least one group.  Groups are vectors, delimited as =[ ...group... ]=.

There is basic layout support and you can use it to collect or differentiate commands.

If you begin a group vector with a string, you get a group heading.  Groups also support some [[https://magit.vc/manual/transient/Group-Specifications.html#Group-Specifications][properties]].  The [[elisp:(describe-symbol transient-group)][group class]] also has a lot of information.




#+BEGIN_SRC elisp
(progn 1 3 5 4 7 2)
#+END_SRC

#+RESULTS:
: 2
